<?php
/**
 * @category   Laurent
 * @package    Laurent_Prerender
 * @copyright  Copyright (c) 2011 Laurent Clouet
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author     Laurent Clouet <laurent35240@gmail.com>
 * 
 * @var $this Laurent_Prerender_Block_Link
 */

?>
<?php if($this->getPrerenderLink() != ''): ?>
<link rel="prerender" href="<?php echo $this->getPrerenderLink(); ?>" />
<?php endif; ?>